# OpenCV Nedir?

Bilgisayarlı görünün amacı : Görüntüleri anlamak ve amaçlarımız doğrultusunda yorumlamaktır.

Örn -> Resimdeki yüzlerin algılanması resimdeki yüzlerin çerçeve içine alınması olabilir. Resimdeki yüzlerin kime ait olduğunu bulunması tanıma 

# Resimlere Giriş

Pixel = dijital görünütnün yapı taşı

Bir görüntüde pixeller alt alta ve yan yana dizilmiştir ve her birinin bir rengi vardır.

Renkler sayılarla ifade edilir. OpenCv fonk. ile pixellerin renk değerlerine erişebiliyoruz. Her pikselin bir adresi(koordinatı var).

# Resim Okuma, Gösterme, Kaydetme

In [1]:
import numpy
import matplotlib
import cv2

Resimleri okuma -> Görsel öğelerin matematiksel arka planı / pixeller ve renk değerlerini okuma

Resmi kaydetme -> Pixel ve renk değerlerini kaydetme

Resmi okuma = cv2.imread()

In [2]:
img = cv2.imread("klon.jpg")
print(img)

[[[159 170 190]
  [ 65  71  78]
  [ 88  85  80]
  ...
  [203 202 211]
  [202 201 210]
  [202 199 208]]

 [[144 152 175]
  [ 52  57  66]
  [ 71  66  63]
  ...
  [206 205 214]
  [205 204 213]
  [204 203 212]]

 [[130 134 158]
  [ 49  49  61]
  [ 63  58  55]
  ...
  [201 201 207]
  [201 201 207]
  [202 200 206]]

 ...

 [[129 120 111]
  [127 118 109]
  [126 117 108]
  ...
  [ 84  79  80]
  [ 87  82  83]
  [ 87  82  83]]

 [[129 120 111]
  [126 117 108]
  [124 115 106]
  ...
  [ 84  79  80]
  [ 80  75  76]
  [ 86  81  82]]

 [[128 119 110]
  [124 115 106]
  [123 114 105]
  ...
  [ 85  80  81]
  [ 81  76  77]
  [ 87  82  83]]]


Resimleri gösterme = cv2.imshow()
Resimleri kaydetme = cv2.imwrite()

In [3]:
cv2.namedWindow("image", cv2.WINDOW_NORMAL) #resmin boyutunda değişiklik yapabilmemizi sağlıyor
cv2.imshow("image", img) #argümanlar:  adı, resmin tutulduğu değişken 
cv2.imwrite("kolon1.jpg",img)
cv2.waitKey(0) #waitKey kullanmazsam resim anlık gelip gidecek ekranda göremeyeceğiz
cv2.destroyAllWindows()

In [4]:
#resmin kod klasöründe bulunmama durumu için:
#img = cv2.imread("C:\\Users\\aysen\\Desktop\\klon.jpg")
#cv2.namedWindow("image", cv2.WINDOW_NORMAL)
#cv2.imshow("image", img)
#cv2.imwrite("C:\\Users\\aysen\\Desktop\\klon1.jpg",img)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

# Pencereyi Yeniden Boyutlandırma Uygulaması

yeniden boyutlandırma = cv2.resize()

In [5]:
import cv2

In [6]:
img = cv2.imread("klon.jpg")
img= cv2.resize(img,(200,400))
cv2.imshow("klon", img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Aspect Ratio (En Boy Oranı) Uygulaması

In [7]:
import cv2
def resizewithAspectRatio (img, width =None, height=None, inter= cv2.INTER_AREA):
    
    dimension = None
    (h,w)= img.shape[:2]
    
    if width is None and height is None:
        return img

    if width is None:
        r = height / float(h)
        dimension = (int(w*r), height)

    else:
        r = width / float(w)
        dimension = (width, int(h*r))

    return cv2.resize(img, dimension, interpolation = inter)

In [8]:
img= cv2.imread("klon.jpg")
img1 =resizewithAspectRatio (img, width =None, height=600, inter= cv2.INTER_AREA) 

In [9]:
cv2.imshow("Orijinal",img)
cv2.imshow("Resized",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Videolara Giriş

Pixeller resimlerin, kareler(frame) ise videoların yapı taşıdır. Her bir frame aslında bir resimdir ve framelerin arka arkaya gelmesi ile video oluşur.

# Video Okuma ve Gösterme

In [10]:
import cv2

In [11]:
# cap değişkeni kullanıyoruz - capture(video yakalama) anlamında geleneksel bir kullanım
cap = cv2.VideoCapture(0) #kameradan okuyacaksak 0 diğer bağlı kamera vb. kullanacaksak sırasıyla 1-2 değişkenlerini giriyoruz
#bilgisayarımızda bulunan bir video kullanacaksak o videonun adresini giriyoruz.
while True:
    ret, frame = cap.read()
    frame=cv2.flip(frame,1) #y'ye göre tersini aldım-aynaladım
    cv2.imshow("Webcam",frame)
    if cv2.waitKey(1) == ord("q"): #klavyeden q ya basınca ekranı kapat
        break
    
cap.release() #cap relase ile işlemi kapatıyoruz, kapatmadan başka işlem yapamam
cv2.destroyAllWindows()

In [12]:
cap = cv2.VideoCapture("antalya.mp4")
while True:
    ret, frame = cap.read()
    if ret == False:
        break
    frame=cv2.flip(frame,1) #y'ye göre tersini aldım-aynaladım
    cv2.imshow("Antalya",frame)
    key=cv2.waitKey(1) #o yaparsam tek bir frame göreceğim
    if key == ord("q"): #klavyeden q ya basınca ekranı kapat
        break
    
cap.release() #cap relase ile işlemi kapatıyoruz, kapatmadan başka işlem yapamam
cv2.destroyAllWindows()

# Video Kaydetme

In [13]:
import cv2

cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

fileName = "GoruntuIsleme\webcam.avi"
codec = cv2.VideoWriter_fourcc('W', 'M', 'V', '2') # codec algoritmalerı tanıyor - ses ve görüntü birleştrmede algoritmalar kullanıyorun
#fourcc = medya verilerindeki codecleri 4 karakter ile tanımlarlar
#girilen değerler video uzantısı ile ilgili
frameRate = 30 #frame oranı
resolution = (640, 480) #çözünürlük

videoFileOutput = cv2.VideoWriter(fileName, codec, frameRate, resolution) #okunan frameleri bu değişkene yazıp dosyalıyorum

while True:
    ret, frame = cap.read()
    frame = cv2.flip(frame,1)
    videoFileOutput.write(frame)

    cv2.imshow("Webcam Live", frame)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

videoFileOutput.release()
cap.release()
cv2.destroyAllWindows()

# Android Kamera Kullanımı

In [14]:
#IP Webcam indirmemiz gerekiyor telefona
import cv2
import numpy as np
import requests

In [ ]:
url= "http:// url //shot.jpg"
while True:
    img_resp = request().get(url)
    img_arr = np.array(bytearray(img_resp.content), dtype=np.uint8)
    img = cv2.imdecode(img_arr,cv2.IMREAD_COLOR)
    img= cv2.resize(img,(640,480))
    
    cv2.imshow("Android Kamera", img)
    
    if cv2.waitKey(1)==27: #Resimde 0 veideoda 1 kullanıyoruz
        break
        
cv2.destroyAllWindows()